### ISSUE TITLE
error in kount_ris_sdk setup

### ISSUE THREAD

**Issue by mwilco03** [Kount/kount-ris-python-sdk#16]
Receive error stated above.

Full text: 
error in kount_ris_sdk setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'py2-ipad'"
 
Remediation 
On line 39 of setup.py add a comma 

37 REQUIRES = (
38    'requests>=2.11.1',
39    'mom>=0.1.3;python_version<"3.0"'**,**
40    'py2-ipaddress>=3.4.1;python_version<"3.0"'
41 )

**Comment by boyankukushev** [comment]
@mwilco03, excuse us for being slow to respond to this issue. I've applied the suggested fix.
